### ISSUE TITLE
Processed 0 files (0 metrics) in /var/spool/nagios/graphios

### ISSUE THREAD

**Issue by Lagadapati11** [shawn-sterling/graphios#105]
my nagios.cfg::

###### Auto-generated Graphios configs #######
process_performance_data=1
service_perfdata_file=/var/spool/nagios/graphios/service-perfdata
service_perfdata_file_template=DATATYPE::SERVICEPERFDATA\tTIMET::$TIMET$\tHOSTNAME::$HOSTNAME$\tSERVICEDESC::$SERVICEDESC$\tSERVICEPERFDATA::$SERVICEPERFDATA$\tSERVICECHECKCOMMAND::$SERVICECHECKCOMMAND$\tHOSTSTATE::$HOSTSTATE$\tHOSTSTATETYPE::$HOSTSTATETYPE$\tSERVICESTATE::$SERVICESTATE$\tSERVICESTATETYPE::$SERVICESTATETYPE$\tGRAPHITEPREFIX::$_SERVICEGRAPHITEPREFIX$\tGRAPHITEPOSTFIX::$_SERVICEGRAPHITEPOSTFIX$\tMETRICTYPE::$_SERVICEMETRICTYPE$
service_perfdata_file_mode=a
service_perfdata_file_processing_interval=15
service_perfdata_file_processing_command=graphios_perf_service
host_perfdata_file=/var/spool/nagios/graphios/host-perfdata
host_perfdata_file_template=DATATYPE::HOSTPERFDATA\tTIMET::$TIMET$\tHOSTNAME::$HOSTNAME$\tHOSTPERFDATA::$HOSTPERFDATA$\tHOSTCHECKCOMMAND::$HOSTCHECKCOMMAND$\tHOSTSTATE::$HOSTSTATE$\tHOSTSTATETYPE::$HOSTSTATETYPE$\tGRAPHITEPREFIX::$_HOSTGRAPHITEPREFIX$\tGRAPHITEPOSTFIX::$_HOSTGRAPHITEPOSTFIX$\tMETRICTYPE::$_HOSTMETRICTYPE$
host_perfdata_file_mode=a
host_perfdata_file_processing_interval=15
host_perfdata_file_processing_command=graphios_perf_host

cfg_dir=/usr/local/nagios/etc/objects

# graphite\_perf\_service
# graphite\_perf\_host

** And added perf commands in include dir to graphios_commands.cfg

define command {
    command_name            graphite_perf_host
    command_line            /bin/mv /var/spool/nagios/graphios/host-perfdata /var/spool/nagios/graphios/host-perfdata.$TIMET$

}

define command {
    command_name            graphite_perf_service
    command_line            /bin/mv /var/spool/nagios/graphios/service-perfdata /var/spool/nagios/graphios/service-perfdata.$TIMET$
}

My log file::
 graphios.py INFO ctrl-c pressed. Exiting graphios.
 graphios_backends.py INFO Carbon Backend Initialized
 graphios.py INFO Enabled backends: ['carbon']
 graphios.py INFO graphios startup.
 graphios.py INFO Processed 0 files (0 metrics) in /var/spool/nagios/graphios
 graphios.py INFO Processed 0 files (0 metrics) in /var/spool/nagios/graphios
 graphios.py INFO Processed 0 files (0 metrics) in /var/spool/nagios/graphios
 
and there were no files inside the spool dir   ( /var/spool/nagios/graphios )

**Comment by Lagadapati11** [comment]
i have resolved this by giving permission to nagios group for spool directory (var/spool/nagios/graphios).And added the apache user to nagios group.

**Comment by mukundparmar** [comment]
In my case same as above error but difference is he is using carbon I am using Influxdb,
my configuration like 
nagios.cfg 

###### Auto-generated Graphios configs #######
process_performance_data=1
service_perfdata_file=/var/spool/nagios/graphios/service-perfdata
service_perfdata_file_template=DATATYPE::SERVICEPERFDATA\tTIMET::$TIMET$\tHOSTNAME::$HOSTNAME$\tSERVICEDESC::$SERVICEDESC$\tSERVICEPERFDATA::$SERVICEPERFDATA$\tSERVICECHECKCOMMAND::$SERVICECHECKCOMMAND$\tHOSTSTATE::$HOSTSTATE$\tHOSTSTATETYPE::$HOSTSTATETYPE$\tSERVICESTATE::$SERVICESTATE$\tSERVICESTATETYPE::$SERVICESTATETYPE$\tGRAPHITEPREFIX::$_SERVICEGRAPHITEPREFIX$\tGRAPHITEPOSTFIX::$_SERVICEGRAPHITEPOSTFIX$\tMETRICTYPE::$_SERVICEMETRICTYPE$
service_perfdata_file_mode=a
service_perfdata_file_processing_interval=15
service_perfdata_file_processing_command=graphios_perf_service
host_perfdata_file=/var/spool/nagios/graphios/host-perfdata
host_perfdata_file_template=DATATYPE::HOSTPERFDATA\tTIMET::$TIMET$\tHOSTNAME::$HOSTNAME$\tHOSTPERFDATA::$HOSTPERFDATA$\tHOSTCHECKCOMMAND::$HOSTCHECKCOMMAND$\tHOSTSTATE::$HOSTSTATE$\tHOSTSTATETYPE::$HOSTSTATETYPE$\tGRAPHITEPREFIX::$_HOSTGRAPHITEPREFIX$\tGRAPHITEPOSTFIX::$_HOSTGRAPHITEPOSTFIX$\tMETRICTYPE::$_HOSTMETRICTYPE$
host_perfdata_file_mode=a
host_perfdata_file_processing_interval=15
host_perfdata_file_processing_command=graphios_perf_host

vim conf.d/graphios_commands.cfg
define command {
    command_name            graphios_perf_host
    command_line            /bin/mv /var/spool/nagios/graphios/host-perfdata /var/spool/nagios/graphios/host-perfdata.$TIMET$
}

define command {
    command_name            graphios_perf_service
    command_line            /bin/mv /var/spool/nagios/graphios/service-perfdata /var/spool/nagios/graphios/service-perfdata.$TIMET$


# cd /var/spool/nagios/
drwxrwsr-x. 2 nagios nagios  4096 Oct 30  2014 cmd
drwxrwxrwx  2 nagios nagios 73728 Jan 13 22:27 graphios


Graphios.cfg 


enable_influxdb09 = True

# Extra tags to add to metrics, like data center location etc.
# Only valid for 0.9
#influxdb_extra_tags = {"location": "la"}

# Comma separated list of server:ports
# defaults to 127.0.0.1:8086 (:8087 if using SSL).
#influxdb_servers = 127.0.0.1:8087

# SSL, defaults to False
#influxdb_use_ssl = True

# Database-name, defaults to nagios
influxdb_db = graphios

# Credentials (required)
influxdb_user = graphios
influxdb_password = graphios

I created above user and database in InfluxDB. 

logs 

January 13 22:30:58 graphios.py DEBUG graphios sleeping.
January 13 22:31:13 graphios.py DEBUG Processing spool directory /var/spool/nagios/graphios
January 13 22:31:13 graphios.py DEBUG deleted /var/spool/nagios/graphios/service-perfdata.1484346659
January 13 22:31:13 graphios.py DEBUG deleted /var/spool/nagios/graphios/host-perfdata.1484346659
January 13 22:31:13 graphios.py INFO Processed 1 files (0 metrics) in /var/spool/nagios/graphios
January 13 22:31:13 graphios.py DEBUG graphios sleeping.
?????

**Comment by mikimtm** [comment]
Same problem here
