### ISSUE TITLE
Config file: log_level not respected.

### ISSUE THREAD

**Issue by whatevsz** [shawn-sterling/graphios#108]
As far as I can see, the `log_level` key in the configuration file is not used at all. The level for the python logging module is set to `INFO` by default, or set to `DEBUG` if `verbose` is set to `True`.

I'd submit a pull request, but was not sure about the best way to go about this. I propose two solutions:

* A new `quiet` config key (and maybe a `--quiet`/`-q` command line switch) that sets the log level to `WARNING`. The existing `log_level` key may be removed/deprecated.

* Using the `log_level` key, with the allowed values being the same as the logging levels for the logging module (`CRITICAL`, `ERROR`, `WARNING`, `INFO`, `DEBUG`).

After consensus on which was is preferred, I will submit a pull request.

**Comment by shawn-sterling** [comment]
I like the 2nd one, but not too fussy. :)
