### ISSUE TITLE
Graphios not able to send metrics data with InfluxDB version 0.12

### ISSUE THREAD

**Issue by itzmesanjib** [shawn-sterling/graphios#114]
Graphios is not able to send metrics data with the latest version of the influxDB 0.12. This is the error i get:
Build URL: http://10.233.18.8:8086/write?u=influxdb&p=influxdb
Failed to send metrics to InfluxDB.                                 Status code: 400: {"error":"database is required"}
Looks like the something was changed on the influxDB with the latest release which now makes a compulsion for the database to be passed as well with the HTTP build url. I did make that change but it again failed complaining that it wasn't able to parse the JSON request.

**Comment by mpetersen42** [comment]
I believe the issue is probably that influx completely deprecated the JSON write protocol used by graphios.

https://docs.influxdata.com/influxdb/v0.12/write_protocols/json/

**Comment by itzmesanjib** [comment]
So does that mean that we would not be able to use the graphios script with recent versions of InfluxDB? I did make a workaround though using the influxDB version 0.11.1. To enable the JSON write protocol , make the following change in the influxdb config file :json-write-enabled = true and restart the services

**Comment by miedzwiedz** [comment]
Now works with influxdb-0.12

--- graphios_backends_old.py	2016-05-11 23:31:23.311977312 +0200
+++ graphios_backends.py	2016-05-11 23:32:05.643777828 +0200
@@ -554,9 +554,9 @@

     def _send(self, server, chunk):
         self.log.debug("Connecting to InfluxDB at %s" % server)
-        json_body = json.dumps(chunk)
-        req = urllib2.Request(self.build_url(server), json_body)
-        req.add_header('Content-Type', 'application/json')
+        #json_body = json.dumps(chunk)
+        req = urllib2.Request(self.build_url(server), chunk)
+        req.add_header('Content-Type', 'application/x-www-form-urlencoded')

         try:
             r = urllib2.urlopen(req, timeout=self.timeout)
@@ -635,9 +635,10 @@
         if len(test_port) < 2:
             server = "%s:%i" % (server, self.default_ports[self.scheme])

-        return "%s://%s/write?u=%s&p=%s" % (self.scheme, server,
+        return "%s://%s/write?u=%s&p=%s&db=%s" % (self.scheme, server,
                                             self.influxdb_user,
-                                            self.influxdb_password)
+                                            self.influxdb_password,
+                                            self.influxdb_db)

     def send(self, metrics):
         """ Connect to influxdb and send metrics """
@@ -663,17 +664,17 @@
             tags = {"check": m.LABEL, "host": m.HOSTNAME}
             tags.update(self.influxdb_extra_tags)

-            perfdata.append({
-                            "timestamp": int(m.TIMET),
-                            "measurement": path,
-                            "tags": tags,
-                            "fields": {"value": value}})
+            perfdata.append('%s,%s value=%s %d' % (
+                path,
+                ','.join(['%s=%s' % (k, v) for k, v in tags.iteritems() if v]),
+                value,
+                int(m.TIMET) * 10 ** 9
+            ))

         series_chunks = self.chunks(perfdata, self.influxdb_max_metrics)
         for chunk in series_chunks:
-            series = {"database": self.influxdb_db, "points": chunk}
             for s in self.influxdb_servers:
-                if not self._send(s, series):
+                if not self._send(s, '\n'.join(chunk)):
                     ret = 0

         return ret
