### ISSUE TITLE
Processing non perfdata in spool directory

### ISSUE THREAD

**Issue by kurtabersold** [shawn-sterling/graphios#120]
I probably have an unconventional setup, but I have two files in the spool directory that are not perfdata. Those are `objects_cache_file` and `state_retention_file` . When Graphios starts, it processes all the data in the directory, including those files.

I suspect this is the reason I get a parse error in the Graphios logs:

```
August 29 23:45:57 graphios_backends.py INFO Carbon Backend Initialized
August 29 23:45:57 graphios.py INFO Enabled backends: ['carbon']
August 29 23:45:57 graphios.py INFO graphios startup.
August 29 23:45:59 graphios.py INFO Processed 4 files (92 metrics) in /opt/nagios/spool
August 29 23:46:14 graphios.py CRITICAL failed to parse label: 'lines' part of perfstring 'lines = 0'
August 29 23:46:14 graphios.py CRITICAL failed to parse label: '0' part of perfstring 'lines = 0'
```

Does Graphios expect to be able to process anything in the spool directory as perfdata? If so, I will make the necessary changes on my fleet, but I do believe this configuration worked in an older version. Currently, I am running master in QA, where I am seeing this issue. I am unsure of the version I was running before, but it was before the automatic naming feature existed.

**Comment by gummiboll** [comment]
IIRC graphios tries to read/parse all files in the spool-directory as perfdata-files unless their name begins with a '_' so this is probably why you are seeing this error.

**Comment by kurtabersold** [comment]
I moved the location of the two files in `nagios.cfg`, and things are better.

I am still getting the parse error, but it's not killing those essential files now.
