### ISSUE TITLE
Influx DB configurations missing in pip install

### ISSUE THREAD

**Issue by onlybytes** [shawn-sterling/graphios#137]
Hi,

I am working on setting up a monitoring system. I thought i will use Graphios to ingest Nagios data into InfluxDB.

I did `pip install graphios`

The influxDB configurations are missing in the graphios.cfg file that is present under /etc/graphios directory.

The version that gets installed is 2.0.3

Am i missing something. Please help.

Thanks,
Mahesh

**Comment by horshack** [comment]
You are write, when installing the software with pip (as recommended in the readme), the influxdb backend is not in the sources. Get the software with "git clone"... I was also working on this for more than an hour...

**Comment by onlybytes** [comment]
Yep. I did that after spending 2 hours.. 
Forgot to post the comment. 

Thank you..

**Comment by sp0rus** [comment]
I feel like this issue should be reopened, since it is still an issue today.
