### ISSUE TITLE
Graphios.py not parsing performance data files

### ISSUE THREAD

**Issue by coltaa** [shawn-sterling/graphios#17]
Hello, 

I tried to use it, but something is not working as expected:

Processing spool directory /usr/local/nagios/var/graphios
Processed 0 files in /usr/local/nagios/var/graphios

and performance data are in:

:/usr/local/nagios/var/graphios# ls -la
total 2756
drwxr-xr-x 2 nagios nagcmd    4096 Apr 29 14:38 .
drwxrwxr-x 6 nagios nagios    4096 Apr 29 15:52 ..
-rw-rw-r-- 1 nagios nagios  124492 Apr 29 15:51 host-perfdata
-rw-rw-r-- 1 nagios nagios 2675162 Apr 29 15:52 service-perfdata

Can you help to understand what is wrong.

Thank you

**Comment by Lagadapati11** [comment]
I also had the similar problem.check weather nagios grp is having write permission into that directory

**Comment by mikimtm** [comment]
Hi, I am having same problem, whatever I do, graphios says either processed Processed 0 files (0 metrics) in /var/spool/nagios/graphios

or 1 flises ( 0 metrics)


Here are my configs 

grep "^[^#;]" /etc/nagios/nagios.cfg
log_file=/var/log/nagios/nagios.log
cfg_file=/etc/nagios/objects/commands.cfg
cfg_file=/etc/nagios/objects/contacts.cfg
cfg_file=/etc/nagios/objects/timeperiods.cfg
cfg_file=/etc/nagios/objects/templates.cfg
cfg_file=/etc/nagios/objects/localhost.cfg
cfg_dir=/etc/nagios/conf.d
object_cache_file=/var/spool/nagios/objects.cache
precached_object_file=/var/spool/nagios/objects.precache
resource_file=/etc/nagios/private/resource.cfg
status_file=/var/spool/nagios/status.dat
status_update_interval=10
nagios_user=nagios
nagios_group=nagios
check_external_commands=1
command_file=/var/spool/nagios/cmd/nagios.cmd
lock_file=/var/run/nagios/nagios.pid
temp_file=/var/spool/nagios/nagios.tmp
temp_path=/tmp
event_broker_options=-1
log_rotation_method=d
log_archive_path=/var/log/nagios/archives
use_syslog=1
log_notifications=1
log_service_retries=1
log_host_retries=1
log_event_handlers=1
log_initial_states=0
log_current_states=1
log_external_commands=1
log_passive_checks=1
service_inter_check_delay_method=s
max_service_check_spread=30
service_interleave_factor=s
host_inter_check_delay_method=s
max_host_check_spread=30
max_concurrent_checks=0
check_result_reaper_frequency=10
max_check_result_reaper_time=30
check_result_path=/var/spool/nagios/checkresults
max_check_result_file_age=3600
cached_host_check_horizon=15
cached_service_check_horizon=15
enable_predictive_host_dependency_checks=1
enable_predictive_service_dependency_checks=1
soft_state_dependencies=0
auto_reschedule_checks=0
auto_rescheduling_interval=30
auto_rescheduling_window=180
service_check_timeout=60
host_check_timeout=30
event_handler_timeout=30
notification_timeout=30
ocsp_timeout=5
perfdata_timeout=5
retain_state_information=1
state_retention_file=/var/spool/nagios/retention.dat
retention_update_interval=60
use_retained_program_state=1
use_retained_scheduling_info=1
retained_host_attribute_mask=0
retained_service_attribute_mask=0
retained_process_host_attribute_mask=0
retained_process_service_attribute_mask=0
retained_contact_host_attribute_mask=0
retained_contact_service_attribute_mask=0
interval_length=60
check_for_updates=1
bare_update_check=0
use_aggressive_host_checking=0
execute_service_checks=1
accept_passive_service_checks=1
execute_host_checks=1
accept_passive_host_checks=1
enable_notifications=1
enable_event_handlers=1
process_performance_data=1
obsess_over_services=0
obsess_over_hosts=0
translate_passive_host_checks=0
passive_host_checks_are_soft=0
check_for_orphaned_services=1
check_for_orphaned_hosts=1
check_service_freshness=1
service_freshness_check_interval=60
service_check_timeout_state=c
check_host_freshness=0
host_freshness_check_interval=60
additional_freshness_latency=15
enable_flap_detection=1
low_service_flap_threshold=5.0
high_service_flap_threshold=20.0
low_host_flap_threshold=5.0
high_host_flap_threshold=20.0
date_format=us
illegal_object_name_chars=`~!$%^&*|'"<>?,()=
illegal_macro_output_chars=`~$&|'"<>
use_regexp_matching=0
use_true_regexp_matching=0
admin_email=nagios@localhost
admin_pager=pagenagios@localhost
daemon_dumps_core=0
use_large_installation_tweaks=0
enable_environment_macros=0
debug_level=0
debug_verbosity=1
debug_file=/var/spool/nagios/nagios.debug
max_debug_file_size=1000000
allow_empty_hostgroup_assignment=0
process_performance_data=1
service_perfdata_file=/var/spool/nagios/graphios/service-perfdata
service_perfdata_file_template=DATATYPE::SERVICEPERFDATA\tTIMET::$TIMET$\tHOSTNAME::$HOSTNAME$\tSERVICEDESC::$SERVICEDESC$\tSERVICEPERFDATA::$SERVICEPERFDATA$\tSERVICECHECKCOMMAND::$SERVICECHECKCOMMAND$\tHOSTSTATE::$HOSTSTATE$\tHOSTSTATETYPE::$HOSTSTATETYPE$\tSERVICESTATE::$SERVICESTATE$\tSERVICESTATETYPE::$SERVICESTATETYPE$\tGRAPHITEPREFIX::$_SERVICEGRAPHITEPREFIX$\tGRAPHITEPOSTFIX::$_SERVICEGRAPHITEPOSTFIX$\tMETRICTYPE::$_SERVICEMETRICTYPE$
service_perfdata_file_mode=a
service_perfdata_file_processing_interval=15
service_perfdata_file_processing_command=graphios_perf_service
host_perfdata_file=/var/spool/nagios/graphios/host-perfdata
host_perfdata_file_template=DATATYPE::HOSTPERFDATA\tTIMET::$TIMET$\tHOSTNAME::$HOSTNAME$\tHOSTPERFDATA::$HOSTPERFDATA$\tHOSTCHECKCOMMAND::$HOSTCHECKCOMMAND$\tHOSTSTATE::$HOSTSTATE$\tHOSTSTATETYPE::$HOSTSTATETYPE$\tGRAPHITEPREFIX::$_HOSTGRAPHITEPREFIX$\tGRAPHITEPOSTFIX::$_HOSTGRAPHITEPOSTFIX$\tMETRICTYPE::$_HOSTMETRICTYPE$
host_perfdata_file_mode=a
host_perfdata_file_processing_interval=15
host_perfdata_file_processing_command=graphios_perf_host











grep "^[^#;]" /etc/graphios/graphios.cfg 
[graphios]
replacement_character = _
spool_directory = /var/spool/nagios/graphios
log_file = /usr/local/nagios/var/graphios.log
log_max_size = 24
log_level = logging.INFO
debug = True
sleep_time = 15
sleep_max = 480
test_mode = False
use_service_desc = False
replace_hostname = True
reverse_hostname = False
enable_carbon = False
carbon_plaintext = False
carbon_servers = 127.0.0.1:2004
enable_statsd = False
statsd_servers = 127.0.0.1:8125
enable_librato = False
librato_whitelist = [".*"]
enable_influxdb = True
enable_influxdb09 = True
influxdb_extra_tags = {"location": "la"}
influxdb_servers = 127.0.0.1:8086
influxdb_user = influx
influxdb_password = notrealpassword
influxdb_line_protocol = True
enable_stdout = False
nerf_stdout = True


ls -la /var/spool/nagios/graphios/
total 4
drwxrwxrwx. 2 nagios nagios  51 Mar 10 11:56 .
drwxr-xr-x. 5 nagios nagios 113 Mar 10 11:56 ..
-rw-r--r--. 1 nagios nagios   0 Mar 10 11:56 host-perfdata
-rw-r--r--. 1 nagios nagios 376 Mar 10 11:56 service-perfdata
