### ISSUE TITLE
Replace dots with underscores

### ISSUE THREAD

**Issue by gjedeer** [shawn-sterling/graphios#58]
I'm using full qualified hostnames in Nagios, like:
define service {
    use             my-web
    host_name       web010.myservice.net
    _graphiteprefix servers.myservice.web010.http
}

I've been using the old Graphios (1.x) until today and my metrics are named:
servers.myservice.web010.http.web010_myservice_net.{size,time}

Unfortunately after upgrade to 2.0 my service names are:
servers.myservice.web010.http.web010.myservice.net.{size,time}

(three dummy tree levels - "web010", "myservice", "net" - before I can reach my metrics).

Can you make it an option to replace dots with underscores, like the old version did? I have replacement_character = _ in my config but it doesn't seem to do anything.

**Comment by shawn-sterling** [comment]
This is now fixed on master.

Sorry about that.

Thank you for reporting the bug.

Have a good day.

**Comment by gjedeer** [comment]
Sorry? Dude, you rock, thank you for this wonderful tool and for fixing this problem!
