### ISSUE TITLE
Works on Python 2.6.6

### ISSUE THREAD

**Issue by squareatom** [shawn-sterling/graphios#62]
I was worried when I saw Python 2.7 as a requirement. But seems to work without issue on RHEL 6.5 w/ Python 2.6.6.

$ cat /etc/redhat-release ; python --version
Red Hat Enterprise Linux Server release 6.5 (Santiago)
Python 2.6.6

**Comment by shawn-sterling** [comment]
Ah, this is a typo on my part. I use it on CentOS 6.x in production. :) 

I will fix the documentation.
