### ISSUE TITLE
graphios not honoring statsd address in graphios.cfg

### ISSUE THREAD

**Issue by cgough** [shawn-sterling/graphios#67]
Just installed graphios-2.0.3 via pip.  Host is ubuntu 14.0.4.  It seems to be ignoring the IP address for statsd in /etc/graphios/graphios.cfg.

/etc/graphios/graphios.cfg sets statsd as backend with IP address:
```
root% cat /etc/graphios/graphios.cfg | grep statsd
# Statsd Details (comment in if you are using statsd)
enable_statsd = true 
# Comma separated list of statsd server IP:Port 's
statsd_server = "10.0.0.19:8125"
#flag the statsd backend as 'non essential' for the purposes of error checking
#nerf_statsd = False
```
Running graphios either from init script or by hand shows the following:

root% /usr/local/bin/graphios.py --config_file=/etc/graphios/graphios.cfg
```
root% /usr/local/bin/graphios.py --config_file=/etc/graphios/graphios.cfg
Statsd backend initialized
Enabled backends: ['statsd']
graphios startup.
Processing spool directory /var/spool/nagios/graphios
sending to statsd at 127.0.0.1:8125
graphite_lines:6
sending to statsd at 127.0.0.1:8125
graphite_lines:0
sending to statsd at 127.0.0.1:8125
graphite_lines:18
sending to statsd at 127.0.0.1:8125
graphite_lines:12
```
I need graphios to honor the statsd IP address in /etc/graphite/graphite.cfg.

**Comment by shawn-sterling** [comment]
Ah, this is a tiny typo in the graphios.cfg, all you need to do to fix it is change the line from statsd_server to statsd_servers . I will fix this in the main branch in a few minutves.

Sorry about the bug.
