### ISSUE TITLE
Refuses to enable InfluxDB

### ISSUE THREAD

**Issue by argais** [shawn-sterling/graphios#81]
Following the instructions I couldnt get it to connect to influxdb.

Running an InfluxDB 0.8.8 fresh install, no ssl, simple password.

Steps I followed.
- Cloned repo, copied graphios*py to /opt/graphios, graphios.cfg to /etc/graphios/
- Set up all the required nagios stuff.
- Edited cfg file
- ./graphios.py --verbose

It doesnt show InfluxDB as backend

My influxdb settings on graphios.cfg are as follows:
```
#------------------------------------------------------------------------------
# InfluxDB Details (comment in if you are using InfluxDB)
#------------------------------------------------------------------------------

#enable_influxdb = False

# Comma separated list of server:ports
# defaults to 127.0.0.1:8086 (:8087 if using SSL).
influxdb_servers = 127.0.0.1:8086

# SSL, defaults to False
#influxdb_use_ssl = True

# Database-name, defaults to nagios
influxdb_db = nagios

# Credentials (required)
influxdb_user = root
influxdb_password = notmyrealpasswd

# Max metrics to send / request, defaults to 250
influxdb_max_metrics = 500

# Flag the InfluxDB backend as 'non essential' for the purposes of error checking
#nerf_influxdb = False
```

Running it: 
```
root@ip-10-0-1-63:/opt/graphios# ./graphios.py --verbose
Enabled backends: []
graphios startup.
Processing spool directory /var/spool/nagios/graphios
Processed 0 files (0 metrics) in /var/spool/nagios/graphios
graphios sleeping.
```

My /var/log/graphios.log
```
June 09 14:54:20 graphios.py INFO Enabled backends: []
June 09 14:54:20 graphios.py INFO graphios startup.
June 09 14:54:20 graphios.py DEBUG Processing spool directory /var/spool/nagios/graphios
June 09 14:54:20 graphios.py INFO Processed 0 files (0 metrics) in /var/spool/nagios/graphios
June 09 14:54:20 graphios.py DEBUG graphios sleeping.
June 09 14:54:22 graphios.py INFO ctrl-c pressed. Exiting graphios.
```

Any ideas?? If I made some dumb mistake please let me know.

**Comment by argais** [comment]
Other information that might be useful, or not :)

```
root@ip-10-0-1-63:/opt/graphios# python --version
Python 2.7.6

root@ip-10-0-1-63:/opt/graphios# cat /etc/issue
Ubuntu 14.04.2 LTS \n \l

root@ip-10-0-1-63:/opt/graphios# uname -a
Linux ip-10-0-1-63 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

root@ip-10-0-1-63:/opt/graphios# pip freeze
adagios==1.6.1
apt-xapian-index==0.45
chardet==2.0.1
Cheetah==2.4.4
cloud-init==0.7.5
configobj==4.7.2
Django==1.5
jsonpatch==1.3
jsonpointer==1.0
Landscape-Client==14.12
oauth==1.0.1
PAM==0.4.2
prettytable==0.7.2
pycrypto==2.6.1
pycurl==7.19.3
pymongo==3.0.1
pymssql==1.0.2
pynag==0.9.1
pyOpenSSL==0.13
pyserial==2.6
python-apt===0.9.3.5ubuntu1
python-debian===0.1.21-nmu2ubuntu2
PyYAML==3.10
requests==2.2.1
simplejson==3.6.5
six==1.5.2
ssh-import-id==3.21
Twisted-Core==13.2.0
Twisted-Names==13.2.0
Twisted-Web==13.2.0
urllib3==1.7.1
zope.interface==4.0.5
```

**Comment by argais** [comment]
Commenting everything related to other backends did the trick.

**Comment by gummiboll** [comment]
Shouldn't be a problem running the influxdb-backend with other backends enabled, however, in your settings you have: #enable_influxdb = False which is probably the problem, remove the comment and add enable_influxdb = True and it should work. :)

**Comment by argais** [comment]
Yup, that worked fine.

The comment in/out thing didnt look intuitive to me, but maybe thats just
me being brazilian and all :)
Thanks for this nice piece of software!

**Comment by shawn-sterling** [comment]
Someone else solved the problem, best day ever!

Thanks Gummiboll.

**Comment by bipinraut** [comment]
i am getting same problem "Processed 0 files (0 metrics) in /var/spool/nagios/graphios"
below is output of my graphios.cfg file 
[graphios]

replacement_character = _
spool_directory = /var/spool/nagios/graphios
log_file = /usr/local/nagios/var/graphios.log
log_max_size = 24
log_level = logging.INFO
debug = True
sleep_time = 15
sleep_max = 480
test_mode = False
use_service_desc = False
replace_hostname = True
reverse_hostname = False
enable_influxdb09 = True
influxdb_extra_tags = {"location": "la"}
influxdb_servers = 127.0.0.1:8086
influxdb_db = mydb
influxdb_user = nagiosuser
influxdb_password = nagios2017
influxdb_max_metrics = 500
nerf_influxdb = False
influxdb_line_protocol = True
enable_stdout = False
nerf_stdout = True

running below command
/usr/bin/graphios.py --spool-directory=/var/spool/nagios/graphios --config_file=/etc/graphios/graphios.cfg --log-file=/tmp/graphios.log --backend=influxd --server=127.0.0.1:8086 --verbose

[root@ip-10-0-0-36 ~]# rpm -qa |grep infl
influxdb-1.2.0-1.x86_64

Pls let me know what is doing wrong
