### ISSUE TITLE
Status code: 400: {"error":"missing measurement"}

### ISSUE THREAD

**Issue by argais** [shawn-sterling/graphios#83]
All data sent to influx 0.9.0 returns this error:

```
Status code: 400: {"error":"missing measurement"}
```

Changing this on the graphios_backends.py 

```
            perfdata.append({
                            "timestamp": int(m.TIMET),
                            "name": path,
                            "tags": tags,
                            "fields": {"value": value}})
```

to

```
            perfdata.append({
                            "timestamp": int(m.TIMET),
                            "measurement": path,
                            "tags": tags,
                            "fields": {"value": value}})
```

Fixed it for me. 
Thing is, I am not sure why I should have to change that, since even the InfluxDB docs use name: in its examples...
Is this the case of changing it on graphios or should I go bug the peeps at InfluxDB?

**Comment by gabrieltholsgard** [comment]
@argais 
Hi, looking in to system monitoring using influxdb for metrics so came across this and saw your question to which I have an answer I think.
It's not documented but if you check this issue you can see that they proposed a change from "name" to "measurement".
https://github.com/influxdb/influxdb/issues/2564

**Comment by Shaps** [comment]
Hi, 
This should be fixed with https://github.com/shawn-sterling/graphios/pull/84
