### ISSUE TITLE
Graphios crashes with OSError No such file or directory

### ISSUE THREAD

**Issue by Ev1l** [shawn-sterling/graphios#86]
I keep getting the error below:
```
August 23 11:54:44 graphios.py CRITICAL couldn't remove file /omd/sites/prod/var/pnp4nagios/spool/service-perfdata.1440356069 error:[Errno 2] No such file or directory: '/omd/sites/prod/var/pnp4nagios/spool/service-perfdata.1440356069'
Traceback (most recent call last):
  File "/usr/bin/graphios.py", line 553, in <module>
    main()
  File "/usr/bin/graphios.py", line 532, in main
    process_spool_dir(spool_directory)
  File "/usr/bin/graphios.py", line 430, in process_spool_dir
    if check_skip_file(perfdata_file, file_dir):
  File "/usr/bin/graphios.py", line 462, in check_skip_file
    if os.stat(file_dir)[6] == 0:
OSError: [Errno 2] No such file or directory: '/omd/sites/prod/var/pnp4nagios/spool/host-perfdata.1440356069'

```
I installed and configured Graphios per the instructions for OMD. I thought maybe it was the version I installed via pip and tried installing from source. Although it took longer for the source install to crash it did eventually do so with that message. I keep thinking it has something to do with the interval between when the data is generated to when it is removed by graphios. I set the sleep_time to 10 seconds and the service_perfdata_file_processing_interval in nagios_npcdmod.cfg to 15. But it eventually just crashes. Any thoughts on what I am doing wrong here?

**Comment by shawn-sterling** [comment]
Hi Ev1l, 
From the name of your directories, it looks like you are running pnp4nagios and graphios and using the same spool directory. This is not ideal as, graphios starts to process a file, then pnp4nagios processes the same file and deletes it. Whichever program grabs it first wins. 

It's no problem to run pnp4nagios and graphios at the same time, you just need to copy the files to an additional separate spool directory for graphios. If look at the pnp4nagios instructions you will find step 2, showing how to copy the files for pnp4nagios and putting them into another spool dir for graphios.

Let me know if this helps.

**Comment by Ev1l** [comment]
Hi Shawn,

Thanks, that seems to have been the part I obviously missed. Sorry the instructions weren't very clear on what to us as the spool directory for the config and for some reason I totally missed that. Thanks for the clarification.
