### ISSUE TITLE
Influxdb0.8 backend failed data push

### ISSUE THREAD

**Issue by alexbarta** [shawn-sterling/graphios#91]
Hi I have found a bug at https://github.com/shawn-sterling/graphios/blob/master/graphios_backends.py#L536

To get it working I had to replace the line with:
 path += "%s." % m.GRAPHITEPREFIX

Hope this helps.

Alex

**Comment by gummiboll** [comment]
Great catch @alexbarta! Made a pull request that fixes my mistake :D

**Comment by shawn-sterling** [comment]
Thanks Alexbarta!
