### ISSUE TITLE
Unable to see data in griffin UI

### ISSUE THREAD

**Issue by nishant-kumar47** [shawn-sterling/graphios#94]
Hi There,

I am sending data to cc_relay. I have grafana interface running over graphite. So when i am sending data from nagios, i cannot see anything appearing on UI. I can see following lines in log. Can you please check if the config is correct. If i am convinced that my graphics part is correct, I will put my energy in troubleshooting it from graphite perspective.

November 16 07:02:45 graphios_backends.py INFO Carbon Backend Initialized
November 16 07:02:45 graphios.py INFO Enabled backends: ['carbon']
November 16 07:02:45 graphios.py INFO graphios startup.
November 16 07:18:30 graphios_backends.py INFO Carbon Backend Initialized
November 16 07:18:30 graphios.py INFO Enabled backends: ['carbon']
November 16 07:18:30 graphios.py INFO graphios startup.
November 16 07:18:30 graphios.py INFO Processed 70 files (0 metrics) in /var/spool/nagios/graphios
November 16 07:18:46 graphios.py INFO Processed 72 files (0 metrics) in /var/spool/nagios/graphios
November 16 07:18:51 graphios.py INFO ctrl-c pressed. Exiting graphios.
November 16 07:37:54 graphios_backends.py INFO Carbon Backend Initialized
November 16 07:37:54 graphios.py INFO Enabled backends: ['carbon']
November 16 07:37:54 graphios.py INFO graphios startup.
November 16 07:37:54 graphios.py INFO Processed 32 files (0 metrics) in /var/spool/nagios/graphios
November 16 07:37:58 graphios.py INFO ctrl-c pressed. Exiting graphios.
/tmp/graphios.log (END)

**Comment by shawn-sterling** [comment]
Hi there, sorry for the delayed response I have been crazy busy lately.

So, it looks like the files that graphios is reading don't have any metrics in them. Meaning, either you don't have a _graphiteprefix or _graphitepostfix for the host/service OR you don't have 'use_service_desc = True' in your config. 

If neither of the above statements are accurate, pastebin your nagios.cfg, your graphios related commands (the ones that copy the file to the spool dir, and one of the hosts/services configs that has a _graphiospre/postfix), one of the files from your /var/spool/nagios/graphios/ dir, and your graphios.cfg.

We should be able to get to the bottom of it. :)

**Comment by nishant-kumar47** [comment]
Hi Shawn,

Actually the error that i am getting is : 
November 24 07:44:24 graphios CRITICAL failed to parse label: 'e2e_soyuz_passback_rt=19,e2e_soyuz_passback_failure=0' part of perfstring 'e2e_soyuz_passback_rt=19,e2e_soyuz_passback_failure=0'
November 24 07:44:24 graphios CRITICAL failed to parse label: 'check_bid_fcap_10kperhour_rtbid=50,check_bid_fcap_10kperhour_rtads=16,check_bid_fcap_10kperhour_failure=0' part of perfstring 'check_bid_fcap_10kperhour_rtbid=50,check_bid_fcap_10kperhour_rtads=16,check_bid_fcap_10kperhour_failure=0'

my perf data looks like:
'DATATYPE::SERVICEPERFDATA	TIMET::1448351146	HOSTNAME::pd0-rtbs07-bid01.sea1.audsci.net	SERVICEDESC::FrequencyCap 1 per hour e2e	SERVICEPERFDATA::check_bid_fcap_1perhour_rtbid=19,check_bid_fcap_1perhour_rtads=na,check_bid_fcap_1perhour_failure=0	SERVICECHECKCOMMAND::FrequencyCap_1_per_hour_e2e_e2e_checks_media_pd0-rtbs07-bid01.sea1.audsci.net_pd0-e2emon01	HOSTSTATE::UP	HOSTSTATETYPE::HARD	SERVICESTATE::OK	SERVICESTATETYPE::HARD'

Can you see where is the mistake:

**Comment by nishant-kumar47** [comment]
So my perf data seems to be separated by semicolon.


I tried replacing ; by , but it didn't work(sorry not very good at python). 
                for metric in metric_array:
                    try:
                      nobj = copy.copy(mobj)
                      (nobj.LABEL, d) = metric.split('=')
                      v = d.split(',')[0]
                      u = v
                      nobj.VALUE = re.sub("[a-zA-Z%]", "", v)
                      nobj.UOM = re.sub("[^a-zA-Z]+", "", u)
                      processed_objects.append(nobj)
                    except:
                      log.critical("failed to parse label: '%s' part of perf"
                                 "string '%s'" % (metric, nobj.PERFDATA))
                      continue

**Comment by nishant-kumar47** [comment]
I was able to solve this one thanks.

**Comment by Lagadapati11** [comment]
how did you solve this ?

**Comment by nishant-kumar47** [comment]
i had differnt issue. I ran nc command on the machine to see what exact msg
is getting tranffered and found that msg was ill formed. Then i changed the
setting in some config file(dont remember it now) to send msg as plain text
and it worked.
